name: Generate Pacman Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: hyper-ayoub

      - name: Commit generated files
        run: |
          git config --global user.name "hyper-ayoub"
          git config --global user.email "hyper-ayoub@users.noreply.github.com"
          git add .
          git commit -m "Generate Pacman graph" || exit 0
          git push
